/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cleung' at '11/29/17 11:43 PM' with Gradle 2.14.1
 *
 * @author cleung, @date 11/29/17 11:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
